### ISSUE TITLE
安卓版会放出来吗？

### ISSUE THREAD

**Issue by Yumipk** [idootop/feiyu-player#1]
挺好看的

**Comment by Yumipk** [comment]
翻出了飞鱼 flutter视频播放器

**Comment by Yumipk** [comment]
翻出了飞鱼 flutter视频播放器

**Comment by idootop** [comment]
感谢关注，飞鱼 Flutter 版本的确支持安卓/iOS，不过最新版本是个人自用且闭源的，而且项目比较老旧，已经不再维护更新了。

根据我的个人使用经验，网页版的飞鱼已经够用了，同时它也是一个完备的 PWA 应用，直接将网页添加快捷方式到桌面，使用体验与原生APP差别不大。（唯一功能上的区别在于，Flutter 版本可以使用 DLAN 投屏）

总之，我个人平常追剧都是用飞鱼网页版，很少用原生 APP。

**Comment by idootop** [comment]
@Yumipk 另外，方便透露下你是从哪里了解到这个项目的吗？最近好像突然多出来许多关注者，我比较好奇来源～

**Comment by Yumipk** [comment]
Tg有群友分享的，资源分享
