### ISSUE TITLE
docker部署提示http.conf文件不存在啥的

### ISSUE THREAD

**Issue by OuOumm** [idootop/feiyu-player#3]
docker部署提示http.conf文件不存在啥的

**Comment by idootop** [comment]
贴下错误日志截图还有你的运行设备环境

**Comment by OuOumm** [comment]
稍等，我在重新拉镜像
![image](https://github.com/idootop/feiyu-player/assets/43441064/83849bb3-ede9-45f8-a14c-29200d29252e)


![image](https://github.com/idootop/feiyu-player/assets/43441064/350b3975-7c23-425d-bc2f-f8d686e1b363)

**Comment by OuOumm** [comment]
![image](https://github.com/idootop/feiyu-player/assets/43441064/018c3c31-d7a0-49c9-a574-0947494fae44)
![image](https://github.com/idootop/feiyu-player/assets/43441064/a0b0cfd3-3359-4b99-9029-71afbaf1324c)

**Comment by OuOumm** [comment]
debian12

VMware虚拟化出来的。

1panel

**Comment by OuOumm** [comment]
删掉
![image](https://github.com/idootop/feiyu-player/assets/43441064/d81573ed-40ef-4778-a3af-a4d7bb99312f)
这条后面跟的-c httpd.conf可以运行了，但是提示404了。

![image](https://github.com/idootop/feiyu-player/assets/43441064/76cca719-4451-4fbe-bce1-55664f46b213)

**Comment by idootop** [comment]
可以在镜像里换一个 http server，我之前选的是 [lipanski/docker-static-website](https://github.com/lipanski/docker-static-website) 非常轻量，可能会有一些兼容性问题。

```dockerfile
# 换个其他的 http-server 镜像
FROM lipanski/docker-static-website:latest
# 产物是在 --from=build /app/feiyu/dist 目录下
COPY --from=build /app/feiyu/dist .
```

**Comment by OuOumm** [comment]
感觉像是httpd.conf文件丢失了。

**Comment by idootop** [comment]
把 lipanski/docker-static-website 版本换到 2.2.1 试试看

**Comment by OuOumm** [comment]
好的，请问具体怎么更换，docker我不太熟。

**Comment by idootop** [comment]
我没用过 1panel，里面可以直接修改 dokerfile 吗？把最后两行改成这样试试：
```dockerfile
FROM lipanski/docker-static-website:2.2.1 # 固定版本号

COPY --from=build /app/feiyu/dist .
```
晚上回去我再更新下镜像，修复这个问题。

**Comment by OuOumm** [comment]
可以的，我尝试一下，辛苦佬了。

**Comment by OuOumm** [comment]
昨天没找到dockerfile修改路径，想问问佬你更新了镜像嘛？

**Comment by idootop** [comment]
昨晚还没搞完，今晚回去更新。另外昨晚我试了下现在的镜像，我在mac上用是正常的，可能跟你系统有关。我稍后更新下docker你再试试看。

**Comment by OuOumm** [comment]
应该是，我是Windows11，VMware虚拟化，amd处理器。

**Comment by idootop** [comment]
镜像更新了，删掉本地的重新拉一下再试试。

**Comment by OuOumm** [comment]
好的佬，辛苦了。

**Comment by OuOumm** [comment]
可以了！牛皮！

**Comment by OuOumm** [comment]
这样吗，我挂载的地方有问题吗？我是想把整个目录挂载出来的。

**Comment by idootop** [comment]
从表现上看，你是把本地文件目录挂载到了容器内，容器内的原始文件被覆盖了。并不是你想要的把容器内的文件共享到本机使用。

**Comment by OuOumm** [comment]
![image](https://github.com/idootop/feiyu-player/assets/43441064/c938b58e-904d-4a18-bbb5-b80020d8d05d)


emm问题是挂载的ye'me也没毛病。

**Comment by OuOumm** [comment]
![image](https://github.com/idootop/feiyu-player/assets/43441064/f22f227e-7567-4146-beda-dce03cc505e7)


确实，不知道为啥，挂载出来的目录就是空的。

**Comment by OuOumm** [comment]
好的，我就说我挂在半天都是空的，而且bash也连不上docker，没办法找。

**Comment by OuOumm** [comment]
我感觉是1panel.......挂载的问题？

服务内部错误: update successful but start failed, err: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./httpd": stat ./httpd: no such file or directory: unknown

![image](https://github.com/idootop/feiyu-player/assets/43441064/c630b0a4-b6bb-4164-a6a2-83b4c862fd5c)


只要我这样挂载，就一定会提示为空，然后我去配置文件看了下

Source:"/var/lib/docker/volumes/feiyu"...........

**Comment by OuOumm** [comment]
确定了，是1panel的问题，两个参数给反了，无语。

**Comment by idootop** [comment]
离谱 😂 不过顺便优化了现在的镜像，支持了下 ARM64/v7

**Comment by OuOumm** [comment]
挺好的，想问下，代理部分只能通过云部署吗？如果要本地部署呢...代理部分建议也弄个docker？

**Comment by idootop** [comment]
暂时没这个计划，有时间看看。如果你对 node 熟悉可以自己改改现在的 proxy 代码。backend runtime 用的是 nextjs ，他们应该有本地部署的相关教程。

**Comment by OuOumm** [comment]
好的，改了点，但是没完全改好（

**Comment by idootop** [comment]
可以先在 vercel 部署下，很方便的。

**Comment by idootop** [comment]
proxy 的 docker 镜像，周末结束之前我加一下吧

**Comment by OuOumm** [comment]
vercel我号被干掉了。。

**Comment by OuOumm** [comment]
我尝试改成node.js运行来着，在我的仓库内，我把代码上传了，node-proxy项目下。

**Comment by idootop** [comment]
> 我尝试改成node.js运行来着，在我的仓库内，我把代码上传了，node-proxy项目下。

依赖 nextjs 框架，直接搬过去应该运行不起来

**Comment by OuOumm** [comment]
> > 我尝试改成node.js运行来着，在我的仓库内，我把代码上传了，node-proxy项目下。
> 
> 依赖 nextjs 框架，直接搬过去应该运行不起来

确实，不过我是直接重写了一个代理，能跑，但是不知道为什么还是被同源限制了

**Comment by idootop** [comment]
飞鱼用的代理协议是特殊定制的，其他的代理服务没法直接用。

**Comment by OuOumm** [comment]
不行，根本部署不出来，太复杂了，想自己独立部署真的好麻烦，好多不兼容啊。

好看但是部署困难（

**Comment by idootop** [comment]
@OuOumm 今天我看看打个 docker 镜像，大概晚上会有时间

**Comment by OuOumm** [comment]
> @OuOumm 今天我看看打个 docker 镜像，大概晚上会有时间

帅锅，怎么样了（

**Comment by idootop** [comment]
我昨天新开了一个 `proxy` 分支，重构了下原来的 proxy 代码结构。docker 镜像处理起来应该也不麻烦，只不过我现在没太多空闲时间，还没有完全弄好。不急的话可以再等等看。

另外，你可以先下载桌面客户端用着，不需要填 proxy 就能用。

**Comment by OuOumm** [comment]
好的 我主要是想网页部署

**Comment by OuOumm** [comment]
> 我昨天新开了一个 `proxy` 分支，重构了下原来的 proxy 代码结构。docker 镜像处理起来应该也不麻烦，只不过我现在没太多空闲时间，还没有完全弄好。不急的话可以再等等看。
> 
> 另外，你可以先下载桌面客户端用着，不需要填 proxy 就能用。

苹果cms是怎么实现不同源策略进行访问的？

**Comment by OuOumm** [comment]
> 没理解你要问的是什么。你是说怎么配置苹果cms，让他的接口支持跨域？应该有很多种方法，如果他自己内部有配置选项就打开，没有的话也可以搭一个 nginx 反向代理，使其支持跨域调用。可以参考我的另一个项目：https://github.com/idootop/x-proxy

啊，我的意思不是实现跨域。

你这个也支持苹果cms的采集站接口对吧。我好奇的是，为什么你这个需要做代理才能访问。你是直接在采集站接口上进行搜索了吗？然后直接获取内容？

因为苹果cms采集完之后，可以直接在浏览器进行播放，不用使用代理啥的。

**Comment by OuOumm** [comment]
好的 懂了

**Comment by OuOumm** [comment]
好的，晓得了谢谢

**Comment by OuOumm** [comment]
吸溜，佬搞好了吗

**Comment by idootop** [comment]
正在构建上传镜像，等会发布新版本

**Comment by OuOumm** [comment]
你尊是我的神（

**Comment by idootop** [comment]
@OuOumm feiyu-proxy [v2.1.0](https://github.com/idootop/feiyu-player/releases/tag/v2.1.0) 已发布，添加了 docker 部署方式。

另外，注意飞鱼 docker 的项目根目录已经从 `/home/statics` 和 `/var/www` 变更到 `/app` 目录下。

**Comment by OuOumm** [comment]
尝试了下，搜索能搜了，但是搜出来的东西不对。

![image](https://github.com/idootop/feiyu-player/assets/43441064/0e0b6cfe-0b6e-4652-8db5-8fa43b4d6624)


配置文件

{
    "version": "2.0.0",
    "name": "默认订阅",
    "lastUpdate": 1718243512409,
    "feiyu": {
        "proxy": "http://192.168.2.165:10111/api/proxy",
        "ipfs": {
            "gateway": "https://nftstorage.link/ipfs/{{cid}}",
            "token": "eyJhb...xxx"
        },
        "videoSources": [
            {
                "key": "视频源",
                "api": "https://api.okzy.org/api.php/provide/vod/from/okm3u8/at/xml"
            },
            {
                "key": "视频源2",
                "api": "https://leshiapi.com/api.php/provide/vod/at/xml"
            },
            {
                "key": "视频源3",
                "api": "https://suoniapi.com/api.php/provide/vod/from/snm3u8/at/xml"
            },
            {
                "key": "视频源3",
                "api": "https://ikunzyapi.com/api.php/provide/vod"
            }
        ]
}

**Comment by OuOumm** [comment]
![image](https://github.com/idootop/feiyu-player/assets/43441064/68d67e3d-be93-4e33-9706-e1db464c10d2)
![image](https://github.com/idootop/feiyu-player/assets/43441064/a0858a21-cde5-4f0d-afd9-35bfb95634a0)

**Comment by idootop** [comment]
据我所知，是你找的这几个视频源不支持搜索，或者压根没法用。

**Comment by OuOumm** [comment]
> 据我所知，是你找的这几个视频源不支持搜索，或者压根没法用。

噢摸，还有这种限制吗，搜嘎（那好吧

**Comment by idootop** [comment]
另外后面有新的问题，请创建新的 issue，这个 issue 先 lock 了。
