### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by Hiram-Wong** [idootop/feiyu-player#5]
我看您的项目采用的是 xgplayer，但我在实际使用xgplayer的兼容性不如 dplayer 这种基于 hls.js 库的。不知道作者是怎么解决的，
同时我看您的项目只用了 xgplayer 和 xgplayer-hls，是对 mpd flv 这种格式不做适配吗

**Comment by Hiram-Wong** [comment]
我看您对搜索结果只做isValidM3U8校验，使用 head 方法比 get 可以减少请求时间。或者先进行请求地址后缀匹配能。

**Comment by idootop** [comment]
1. 不喜欢 dplayer 自带的默认皮肤
2. 迄今为止未遇到 xgplayer 兼容性太差的场景
3. 据我所知 xgplayer-hls 背后也是基于 hls.js
4. 主要适配 m3u8 格式视频源，暂不考虑 flv 格式的视频播放
5. isValidM3U8 校验最好是能完整解析 .m3u 播放列表内的实际内容，仅从响应 code 无法保证资源的有效性。

如果你有更好的想法或实现，欢迎 PR。

**Comment by idootop** [comment]
PS: 不晓得您对飞鱼 Player 还有没有印象，当时是和 ZY Player 同时期的产品 😂 后来主要是我个人自用

**Comment by Hiram-Wong** [comment]
xgplayer-hls.js是基于hls.js，xgplayer-hls是字节改的。
我在 zy 中使用xgplayer-hls库会经常遇到要么加载失败，或者播着播着就失败了，就很离谱。

**Comment by idootop** [comment]
我不喜欢做大而全的东西，恰到好处的精简是我所追求的。

从这个项目的界面与功能的设计上，您应该能够感知到一二。

**Comment by Hiram-Wong** [comment]
> 我不喜欢做大而全的东西，恰到好处的精简是我所追求的。
> 
> 从这个项目的界面与功能的设计上，您应该能够感知到一二。

是的，但是 cms 的源质量层次不齐，所以后才引入各种东西

**Comment by idootop** [comment]
> 我在 zy 中使用xgplayer-hls库会经常遇到要么加载失败，或者播着播着就失败了

感谢分享，我的确也会遇到这种情况，但大多是因为视频资源本身要求的网络环境较高，

对我个人的使用体验来说，完全在可接受的范围内，故西瓜 player 暂时还算满足需求。

**Comment by Hiram-Wong** [comment]
tauri 坑挺多的，哈哈哈
web 方案确实是一个不错的选择。加油吧，我看还好多功能都是即将到来

**Comment by idootop** [comment]
> tauri 坑挺多的，哈哈哈

超级多，不过基本都搞定了，哈哈哈

这里分享一些踩坑的心得体验：https://del.wang/projects/product/feiyu?from=pinned

**Comment by Hiram-Wong** [comment]
> > tauri 坑挺多的，哈哈哈
> 
> 超级多，不过基本都搞定了，哈哈哈
> 
> 这里分享一些踩坑的心得体验：https://del.wang/projects/product/feiyu?from=pinned

哈哈哈哈，所以我选择了 electron，tauri 我放弃了，有些无法实现。rust 让我死心。不过你这个单 cms 应该问题不大

**Comment by Hiram-Wong** [comment]
等你开发完，我就不搞zy 了，哈哈哈哈。有机会可以留个联系方式交流一下

**Comment by idootop** [comment]
> 等你开发完，我就不搞zy 了，哈哈哈哈。有机会可以留个联系方式交流一下

目前我个人用起来已经足够了，所以现在也没啥继续向下开发的动力和必要。

剩下的无非是加一下对直播源的支持，历史播放记录，进度恢复，收藏，影评，下载之类的小功能，有没有都无伤大雅。

> 联系方式

可以关注下我的[个人微信公众号](https://del.wang/about)，后台回复一下我，发你联系方式。

**Comment by idootop** [comment]
@Hiram-Wong 最近能在 Web 上直接访问的资源感觉越来越少了，质量也都参差不齐，还是 17 年那会儿爽啊～

另外我也遇到了你说的兼容性的问题，根据我的观察有些资源站的资源是加密的，播放起来兼容性不是很好，目前只能舍弃这一部分。

**Comment by Hiram-Wong** [comment]
> @Hiram-Wong 最近能在 Web 上直接访问的资源感觉越来越少了，质量也都参差不齐，还是 17 年那会儿爽啊～
> 
> 另外我也遇到了你说的兼容性的问题，根据我的观察有些资源站的资源是加密的，播放起来兼容性不是很好，目前只能舍弃这一部分。

最近有进入的，不知道你看新闻没

**Comment by idootop** [comment]
原来如此，有关键词没，搜索下

**Comment by Hiram-Wong** [comment]
> > @Hiram-Wong 最近能在 Web 上直接访问的资源感觉越来越少了，质量也都参差不齐，还是 17 年那会儿爽啊～
> > 另外我也遇到了你说的兼容性的问题，根据我的观察有些资源站的资源是加密的，播放起来兼容性不是很好，目前只能舍弃这一部分。
> 
> 最近有进入的，不知道你看新闻没

https://news.cyol.com/gb/articles/2024-07/07/content_lbLLeZFWRO.html

刚刚公众号留了联系方式

**Comment by idootop** [comment]
> xgplayer-hls.js是基于hls.js，xgplayer-hls是字节改的。
> 我在 zy 中使用xgplayer-hls库会经常遇到要么加载失败，或者播着播着就失败了，就很离谱。

最近经常遇到，准备扒一下[这个站](https://www.nunuys.com/dsj/72233)的播放器配置，然后写个自定义的西瓜播放器 hls 插件。
PS：目前接触下来感觉这个播放比较稳，看他底层用的是[这个项目](https://github.com/Novage/p2p-media-loader)，支持P2P加速，刚好用上。

**Comment by idootop** [comment]
> xgplayer-hls.js是基于hls.js，xgplayer-hls是字节改的。 

@Hiram-Wong  额，我是看过他们源码之后才发现 [xgplayer-hls.js](https://www.npmjs.com/package/xgplayer-hls.js) 是基于 hls.js 适配的，当时还在迷惑 xgplayer-hls 和 xgplayer-hls.js 有什么区别，看官方文档里的 demo 是用 xgplayer-hls 就用这个了，经常提示解析失败。 

换到 [xgplayer-hls.js](https://www.npmjs.com/package/xgplayer-hls.js)  之后，调了一下默认的[加载参数](https://github.com/idootop/feiyu-player/commit/48e46d772eb8bf35d383428264972cafa2c24171#diff-ba10e04d2eba20d5909303b27fc1b2cc80a465682cffef432e8f72a6d527a9daR133)之后没再遇到加载问题了，纵享丝滑。

**Comment by Hiram-Wong** [comment]
> > xgplayer-hls.js是基于hls.js，xgplayer-hls是字节改的。
> 
> @Hiram-Wong 额，我是看过他们源码之后才发现 [xgplayer-hls.js](https://www.npmjs.com/package/xgplayer-hls.js) 是基于 hls.js 适配的，当时还在迷惑 xgplayer-hls 和 xgplayer-hls.js 有什么区别，看官方文档里的 demo 是用 xgplayer-hls 就用这个了，经常提示解析失败。
> 
> 换到 [xgplayer-hls.js](https://www.npmjs.com/package/xgplayer-hls.js) 之后，调了一下默认的[加载参数](https://github.com/idootop/feiyu-player/commit/48e46d772eb8bf35d383428264972cafa2c24171#diff-ba10e04d2eba20d5909303b27fc1b2cc80a465682cffef432e8f72a6d527a9daR133)之后没再遇到加载问题了，纵享丝滑。

加啥参数了

**Comment by idootop** [comment]
@Hiram-Wong  就是简单延长下预加载的时长和各种超时/重试时间。

<img width="736" alt="图片" src="https://github.com/user-attachments/assets/a014da93-ad66-450b-b58e-82fd56a080e3">

**Comment by Hiram-Wong** [comment]
在 h265 的表现上[xgplayer-hls.js](https://www.npmjs.com/package/xgplayer-hls.js)不如[xgplayer-hls](https://www.npmjs.com/package/xgplayer-hls)
