### ISSUE TITLE
nginx 代理二级目录以及 docker 无法进入容器问题

### ISSUE THREAD

**Issue by Hraulein** [idootop/feiyu-player#7]
一、Nginx 代理二级目录配置
> 这是 nginx 反向代理配置
```
    location /feiyu/ {
        proxy_pass http://127.0.0.1:4399/;  
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
    }
```
我在使用您的项目时遇到了关于 Nginx 代理二级目录配置方面的问题。具体来说，我想要将通过 Nginx 代理 /feiyu/ 路径的请求转发到后端服务，但不太清楚如何正确地配置 Nginx。

例如，我希望将请求 `http://127.0.0.1:4399/` 代理到 `https://my.domain.com/feiyu/`，但是在实现过程中，似乎没有正确地处理路径，导致后端服务无法接收到预期的请求。

请问，是否能提供关于如何正确配置 Nginx 以实现这种代理的例子或指导？

二、Docker 无法进入容器的问题
> 这个是我的 docker compose 配置
``` docker
feiyu:
    image: idootop/feiyu:latest
    container_name: feiyu
    restart: always
    ports:
      - "4399:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```

我在使用 Docker 时也遇到一个问题。由于所使用的 Docker 镜像非常精简，容器内没有 bash、sh 或其他常用命令可用，使得无法通过 docker exec 命令进入容器进行调试和操作。
对此，有没有推荐的解决方案？比如能否提供一些建议，帮助我在这种情况下进入容器，或是如何在构建镜像时确保可以访问容器？

期待您的回复!

**Comment by idootop** [comment]
1. 自己问 ChatGPT 如何配置 Nginx 反代。不过在我看来仅通过反代到二级目录是无效的，会干扰js文件的正确加载和pwa。这个项目不考虑二级目录的场景，如果你想要这么做，请自行修改源码，我不会提供任何指导。
2. 飞鱼的 Docker 镜像是一个精简的静态网站，你可以理解成纯静态文件，没必要进去查看什么东西。
